#install Java 1.8
FROM efaille/ubuntu
RUN sudo apt-get update
RUN sudo apt-get -y install software-properties-common
RUN \
        sudo add-apt-repository ppa:webupd8team/java && \
        sudo apt-get update
RUN echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
RUN sudo apt-get -y install oracle-java8-set-default && \
        sudo apt-get clean
# Install maven
RUN apt-get update && apt-get install -y maven
# Install git
RUN apt-get -y update && apt-get install -y git
RUN git clone https://github.com/vineetkarandikar/coding-task.git
RUN cd coding-task && mvn clean install
expose 8080

